apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-llm

namePrefix: vllm-

resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: multi-turn-benchmark
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: "http://qwen-vllm-lb.demo-llm.svc.cluster.local:8000/v1"
