apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-llm

namePrefix: llm-d-

resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: multi-turn-benchmark
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: "http://openshift-ai-inference-openshift-default.openshift-ingress.svc.cluster.local/demo-llm/qwen/v1"
