apiVersion: v1
kind: Service
metadata:
  name: qwen-vllm-lb
  namespace: demo-llm
spec:
  type: ClusterIP
  selector:
    app: isvc.qwen-vllm-predictor
  ports:
    - port: 8000
      targetPort: 8000